name: Backup to S3

on:
  push:
    branches:
      - main # Adjust branch name as per your needs

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1 # Replace with your S3 bucket region

      - name: Backup to S3
        run: |
          aws s3 sync . s3://orxabackup --delete
